### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by phuongortheeast** [ChristianChiarulli/LunarVim#281]
Some icons in my lunarvim are stretched vertically (lua icon, C/C++, python, etc) and one shows a chinese character instead of the actual icon.

**Comment by rebuilt** [comment]
Do you have a nerd font installed on your system?  https://www.nerdfonts.com/

**Comment by phuongortheeast** [comment]
Yes, I did installed ttf-nerd-fonts-symbols

**Comment by rebuilt** [comment]
https://github.com/ryanoasis/nerd-fonts/issues/37

**Comment by rebuilt** [comment]
Also, I had the same problem with the chinese character showing up until I downloaded Fira Code from nerdfonts

**Comment by phuongortheeast** [comment]
I did some digging and found that Fira Code doesn't work in xfce4-terminal so I might have to change it to st. The link wasn't very helpful sadly. Can I fix this using a vim command or something similar?
No I'm not using mono fonts

**Comment by rebuilt** [comment]
There is no vim command to fix your font problems.  You have to set up your system.

You installed ttf-nerd-fonts-symbols.  I'm pretty sure it provides symbols but not letters.  I think what you need is a package that includes both.  Choose a font  from this list 

```bash
nerd-fonts-cascadia-code, nerd-fonts-fira-code, nerd-fonts-hack, nerd-fonts-iosevka, nerd-fonts-jetbrains-mono, nerd-fonts-overpass, nerd-fonts-roboto-mono, nerd-fonts-source-code-pro, nerd-fonts-terminus, nerd-fonts-ubuntu-mono
```
And then install it with (I'm assuming arch since you installed an arch package)
```bash
sudo pacman -S nerd-fonts-fira-code
```
To make sure you've correctly installed your font

```bash
fc-list | grep -i "Fira"
```

Then you have to configure your terminal.  Make sure your terminal supports nerd fonts, i.e. terminator, alacritty, kitty.  

This is the font section of my alacritty config: ~/.config/alacritty/alacritty.yml

```yml
# Font configuration (changes require restart)
font:
  # The size to use.
  size: 14
  #  The normal (roman) font face to use.
  normal:
    family: Fira Code
    # Style can be specified to pick a specific face.
    style: Medium

  # The bold font face
  bold:
    family: Fira Code
    # Style can be specified to pick a specific face.
    style: Bold

  # # The italic font face
  italic:
    family: Fira Code
    # Style can be specified to pick a specific face.
    style: Italic
```
